version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://neondb_owner:npg_Ns01oQvrTMSt@ep-gentle-darkness-aov8xmg7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - CLIENT_URL=http://localhost
      - STRIPE_SECRET_KEY=sk_test_51RuZOtAA8WJ2jERKuDBqzYCU0XF1bJwM8y7B7UEECuvmLkqNn0UQcUgPVcnaS15xjKABQ5lZL0hFAf9Gwn1LqsVh00vcAupFyB
      - CLOUDINARY_CLOUD_NAME=dzmsihnam
      - CLOUDINARY_API_KEY=261764173438511
      - CLOUDINARY_API_SECRET=wjE-Ay8qKOu4lUx9EjIRY9UhBHM
      - FIREBASE_PROJECT_ID=myshopee-6614d
      - FIREBASE_CLIENT_EMAIL=unmeshbhangale41@gmail.com
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
